From DEV to Main
stepancar-web-programming/2023-fall-lab-portfolio-makarov-s.-l. pull request #16
Opened 2024-02-28 17:11 UTC by semonmakarov

2024-02-29 22:49 UTC, stepancar commented on src/App.css
> +img {
Судя по логике, которую я тут вижу - этот файл стилей ответственен за общие стили приложения. 

.section-title , .section  уже не относятся к общим стилям.
Давайте наведем порядок

2024-02-29 22:50 UTC, stepancar commented on src/App.css
> +}
Этот стиль специфичен для компонента который описывает этот элемент

2024-02-29 22:53 UTC, stepancar commented on src/components/aboutMe/AboutMe.jsx
> +                <img src="aboutMe.jpg" className="aboutMe-img" />
если вы подключите линте для accessability вы заметите что не хватает некоторых аттрибутов

https://www.npmjs.com/package/eslint-plugin-jsx-a11y

И вам на это укажет автоматика, а ревьюер не будет тратить на это время

2024-02-29 22:55 UTC, stepancar commented on src/components/aboutMe/AboutMe.jsx
> +                    <div className="aboutMe-title-container">
Обратите внимание что при таком подходе вы можете столкнуться с тем что вам нужно поддерживать уникальность имени классов или же заботиться о повышении специфичности селекторов. Вместе с react-create-app в комплекте идет https://github.com/css-modules/css-modules
Попробуйте использовать их

2024-02-29 22:56 UTC, stepancar commented on src/components/contact/Contact.jsx
> +                    <p>Телефон: +7 (933) 200-1407</p>
Давайте сделаем так чтобы при нажатии на телефон открывался стандартный диалог для звонка

2024-02-29 22:56 UTC, stepancar commented on src/components/contact/Contact.jsx
> +                    <p>Email: semon.makarov.2003@mail.ru</p>
Давайте сделаем так, чтобы при нажатии открывался стандартный почтовый клиент

2024-02-29 23:01 UTC, stepancar commented on package.json
> +  "scripts": {
Не хватает автоматизации проверки кода на соответствие гайдлайна. Добавьте eslint/ csslint, интегрируйте с github actions

2024-02-29 23:01 UTC, stepancar requested changes
Оставил комментарии

2024-03-01 11:34 UTC, semonmakarov commented on src/App.css
> +img {
Исправил, выделил специфические стили в отдельный файл

2024-03-01 11:35 UTC, semonmakarov commented on src/components/aboutMe/AboutMe.jsx
> +                <img src="aboutMe.jpg" className="aboutMe-img" />
Исправил

2024-03-01 11:35 UTC, semonmakarov commented on src/components/aboutMe/AboutMe.jsx
> +                    <div className="aboutMe-title-container">
Благодарю! Использовал, изменил большую часть проекта

2024-03-01 11:35 UTC, semonmakarov commented on src/components/contact/Contact.jsx
> +                    <p>Телефон: +7 (933) 200-1407</p>
Сделано

2024-03-01 11:35 UTC, semonmakarov commented on src/components/contact/Contact.jsx
> +                    <p>Email: semon.makarov.2003@mail.ru</p>
Сделано

2024-03-01 11:36 UTC, semonmakarov commented
Осталась реализация GitHub Actions

2024-03-02 01:39 UTC, stepancar commented on src/specificStyles.css
> +    /* font-family: Poppins, sans-serif; */
Давайте наведем порядок, удалим то, что не нужно

2024-03-02 01:42 UTC, stepancar commented on package.json
> +    "jest-watch-typeahead": "^1.0.0",
У нас с вами выше уже кажется была дискуссия про dependencies/devDependencies. Давайте еще раз разберемся в этом вопросе

2024-03-02 01:43 UTC, stepancar commented on scripts/start.js
> +'use strict';
Можете пояснить по какой причине вам пришлось сделать eject?

2024-03-02 01:46 UTC, stepancar commented on .github/workflows/eslint.yml
> +        run: npx eslint . --config .eslintrc.js --ext .js,.jsx,.ts,.tsx --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
обратите внимание на то, что кофигурация локально и на ci отличается.

Самый простой способ добиться консистентности - избегать передачи кастомных параметров в ci скриптах.

Тут должно быть что-то очень простое

тип npm run lint

2024-03-02 01:47 UTC, stepancar commented on .github/workflows/eslint.yml
> +        run: npx eslint . --config .eslintrc.js --ext .js,.jsx,.ts,.tsx --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
npm скрипты как раз и берут на себя инкапсуляцию всей логики.

Это похоже на паттерн в других языках программирования когда скрипты выносят в makefile

2024-03-02 21:30 UTC, semonmakarov commented on src/specificStyles.css
> +    /* font-family: Poppins, sans-serif; */
Сделано

2024-03-02 21:48 UTC, semonmakarov commented on scripts/start.js
> +'use strict';
Была идея реализовать css modules через изменение файла webpack.config.dev.js, поэтому сделал eject
https://habr.com/ru/articles/335244/
https://stackoverflow.com/questions/60077172/running-npm-run-eject-to-use-css-modules
Но потом было решено реализовать «по-обычному»

2024-03-02 21:52 UTC, semonmakarov commented on package.json
> +    "jest-watch-typeahead": "^1.0.0",
То, что было добавлено в dependencies при установке reject нужно вручную перенести в dependencies/devDependencies?

2024-03-02 21:57 UTC, semonmakarov commented on src/App.css
> +}
Исправлено

2024-03-03 10:21 UTC, semonmakarov commented on scripts/start.js
> +'use strict';
Если требуется, я могу перезалить проект заново, добавив файлы в новое приложение

2024-03-03 17:30 UTC, stepancar approved these changes
Как только будут починены проверки на CI и конфликты - пожалуйста, смержите ПР

2024-03-04 05:50 UTC, semonmakarov commented
> Как только будут починены проверки на CI и конфликты - пожалуйста, смержите ПР
Степан Денисович, такой вопрос.
Было решено создать новую ветку dev2 (откуда вы можете увидеть pull request в  main), где я откатил проекта до установки eject, так с ним возникало большое количество ошибок при разработке GitHub Actions.
Как лучше поступить? Очистить текущую ветку и сделать merge с исправленным проектом? Или залить можно проект в main в dev2, чтобы текущий pull остался?

2024-03-05 17:47 UTC, stepancar commented
@semonmakarov , по хорошему, желательно сделать все чтобы вмержить ПР, в котором мы вели дискуссию, тогда история сохранится. Но в данном проекте это не принципиально

2024-03-10 23:10 UTC, stepancar commented
@semonmakarov , пожалуйста закройте все не актуальные Prs

2024-06-18 17:02 UTC, closed without merging