Dev
stepancar-web-programming/2023-fall-lab-portfolio-makarov-s.-l. pull request #8
Opened 2024-02-26 08:35 UTC by semonmakarov

2024-02-26 09:06 UTC, stepancar requested changes
Вы прислали на ревью код который написан не вами.
Вот пример похожего сайта на ваш. 
https://abdulwhbhussain.github.io/
Нет уверенности в том что это и есть референс, возможно в качестве референса был взят другой репозиторий.
Копирование - это часть работы программиста. Нет ничего зазорного в копировании. Однако, суть этого задания разобраться в предмете. В данном случае у меня нет уверенности в том что вы разобрались в написанном коде.

Я потратил свое время чтобы просмотреть вашу лабораторную работу.
Пожалуйста, в след раз присылайте код написанный вами. если вы делали проект основываясь на каком-то референсе - указывайте его явно

2024-02-26 09:08 UTC, stepancar commented on app/src/components/qualification/Qualification.jsx
> +                            </div>
В резюме у вас написано другое
https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-makarov-s.-l./blob/524e8be5b11a208817679fb023e6f7bde9ca0acf/app/src/assets/CV_Makarov_S_L.pdf

2024-02-26 10:41 UTC, semonmakarov commented on app/package.json
> +    "@testing-library/user-event": "^13.5.0",
Исправил в merge 7

2024-02-26 10:45 UTC, semonmakarov commented on app/src/components/qualification/Qualification.jsx
> +                            </div>
Да, я действительно вдохновлялся другой работой, работу написал я сам. Могу объяснить любую часть кода. Где-то я действительно оставил информацию, как и в шаблоне, потому что мне показалась более важным показать работу сайта. Слайдер, например, я использовал другой. 
Весь код я написал «своей рукой», при этом, да, действительно, копируя, но разбираясь в каждой строчке.
Если требуется я могу добавить какую-то функциональность

2024-02-26 10:47 UTC, semonmakarov commented on app/src/components/qualification/Qualification.jsx
> +                            </div>
Также я понимал, что данные не соответствуют тем, которые в резюме, но повторюсь, что я видел задачу сделать «шаблон». Прошу прощения за мое недопонимание. 
Надеюсь на ваше понимание. Готов добавить какую-то функциональность.

2024-02-26 11:46 UTC, stepancar commented on app/src/components/qualification/Qualification.jsx
> +                            </div>
К сожалению, не могу принять эту работу.
Если вы видели задачу как "сделать шаблон" - то я бы ожидал шаблон сделанный вами, а не шаблон, которых сотни на гитхабе https://www.buymeacoffee.com/crypticacoder/e/85393
Ваши промежуточные коммиты почти пофайлово соответствуют коммитам других людей.
Пример
https://github.com/potlamohansai/portfolio-website/commit/1d25e7f8f57cc56b43529d3161e78cd881965cea#diff-2301f54d139d5bca0897be42d5bb48373ac2238fb2245764bdfed06e708b7c2f

Жду от вас другую работу.

2024-02-26 11:59 UTC, stepancar commented on app/package.json
> +    "@testing-library/user-event": "^13.5.0",
Судя по внесенным изменениям вы не разобрались в вопросе. Обратите внимание react-slick, например - это не devDependency

2024-02-27 20:08 UTC, semonmakarov commented on app/src/components/qualification/Qualification.jsx
> +                            </div>
Здравствуйте!
Прикрепил новую работу, работал над ней усердно!
Жду ваших комментариев

2024-02-28 07:34 UTC, closed without merging